FROM node:22-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY package.json package-lock.json ./

RUN npm ci --omit=dev --no-audit --no-fund

COPY .next ./.next
COPY public ./public
COPY server.mjs ./server.mjs
COPY next.config.ts ./next.config.ts

EXPOSE 3000

CMD ["node", "server.mjs"]